// svelte-speed/src/Rainbow.svelte
<script>
  const rainbowColor = ['red', 'orange', 'yellow', 'green', 'blue', 'navy', 'purple'];
  export let start;
  export let index;
  $: color = '';
  $: if (start) {
    setTimeout(() => {
      if (index === 0) {
        console.time();
      } else if (index === 5000) {
        console.timeEnd();
      }
      color = rainbowColor[index % 7];
    }, 1);
  }
</script>

<div class={`${color} wrap`} />

<style>
  .wrap {
    border: 1px solid;
    width: 20px;
    height: 20px;
  }
  .red {
    background-color: red;
  }
  .orange {
    background-color: orange;
  }
  .yellow {
    background-color: yellow;
  }
  .green {
    background-color: green;
  }
  .blue {
    background-color: blue;
  }
  .navy {
    background-color: navy;
  }
  .purple {
    background-color: purple;
  }
</style>

// react-speed/src/Rainbow.tsx
import React, { useEffect, useState } from 'react';
import classNames from 'classnames/bind';
import './App.css';
import styles from './Rainbow.module.scss';

const rainbowColor = ['red', 'orange', 'yellow', 'green', 'blue', 'navy', 'purple'];

type Props = {
  start: boolean;
  index: number;
};
const cx = classNames.bind(styles);
function Rainbow({ start, index }: Props) {
  const [color, setColor] = useState('');

  useEffect(() => {
    if (start) {
      setTimeout(() => {
        if (index === 0) {
          console.time();
        } else if (index === 5000) {
          console.timeEnd();
        }
        setColor(rainbowColor[index % 7]);
      }, 1);
    }
  }, [start, index]);
  return <div className={cx(styles.wrap, styles[color])}></div>;
}

export default Rainbow;
