// react-speed/src/App.tsx
import React, { useCallback, useState } from 'react';
import logo from './logo.svg';
import './App.css';
import Rainbow from './Rainbow';

function App() {
  const array = Array(2001).fill(0);
  const [start, setStart] = useState(false);

  const onStart = useCallback(() => {
    setStart(true);
  }, [setStart]);

  return (
    <div className="App">
      <div className={'header'}>
        <button className={'btn'} onClick={onStart}>Start</button>
      </div>
      {array.map((value, index) => (
        <Rainbow key={index} start={start} index={index} />
      ))}
    </div>
  );
}

export default App;

// svelte-speed/src/App.svelte
<script>
  import Rainbow from './Rainbow.svelte';
  const arr = new Array(5001).fill(0);
  $: start = false;
  const onStart = () => {
    start = true;
  };
</script>

<div class="app">
  <div class="header">
    <button class="btn" on:click={onStart}>strat</button>
  </div>
  {#each arr as a, index}
    <Rainbow {start} {index} />
  {/each}
</div>

<style>
  .app {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width: 100%;
  }
  .btn {
    height: 30px;
  }
  .header {
    height: 50px;
    width: 100%;
  }
</style>
